### PR TITLE
Revert previous commit and fix again.

### PR DESCRIPTION
**Pull request by cubarco**
My previous commit #23 causes lags. This one may be a better solution.

### CODE REVIEW

**Comment by gabrielelana** [comment]
I thought that `setlocal spelllang+=cjk` would not fix the issue because I read that the spell checking for japanese, chinese, and the like is awful

If you sai that this is a fix for you then there is no need to put that configuration in `vim-markdown` plugin, just put it in your `~/.vimrc` as `set spelllang=en,cjk` and you should be good also for other type of files that have spell checking enabled

What do you think?

**Comment by cubarco** [comment]
Yeah, it is rather a workaround than a solution. I'll close this pull request. Sorry for disturbing.

**Comment by gabrielelana** [comment]
@cubarco nothing to be sorry about, thanks to you I learned something new :+1:

**Comment by cubarco** [comment]
It's my pleasure!

**Pull request closed without merging**
